export const exampleEmployees = [
  ["Amelia Garcia", "0793745281", "Product Manager", "11/04/2018"],
  ["Oliver Lopez", "0725896347", "Marketing Specialist", "23/07/2022"],
  ["Emma Williams", "0768435129", "Sales Representative", "05/01/2016"],
  ["James Thomas", "0741592638", "Software Engineer", "18/11/2020"],
  ["Sophia Miller", "0712365478", "Data Analyst", "09/09/2021"],
  ["Noah Wilson", "0789741253", "UX Designer", "02/03/2019"],
  [
    "Charlotte Anderson",
    "0755588899",
    "Human Resources Generalist",
    "29/10/2017",
  ],
  ["Henry Garcia", "0763214587", "Financial Analyst", "15/06/2023"],
  ["Olivia Brown", "0778945612", "Operations Manager", "21/08/2015"],
  ["Lucas Johnson", "0711122233", "Software Engineer", "14/02/2024"],
  [
    "Evelyn Rodriguez",
    "0744477788",
    "Customer Support Specialist",
    "07/12/2019",
  ],
  ["William Smith", "0788899900", "Product Manager", "19/04/2018"],
  ["Mia Davis", "0752535456", "Marketing Specialist", "30/06/2016"],
  ["Benjamin Williams", "0798765432", "Data Analyst", "13/05/2022"],
  ["Liam Hernandez", "0730313233", "UX Designer", "25/11/2020"],
  ["Isabella Taylor", "0747484950", "Human Resources Generalist", "08/07/2017"],
  ["Elijah Gonzalez", "0765676869", "Financial Analyst", "16/09/2021"],
  ["Amelia Thomas", "0789878987", "Operations Manager", "03/01/2019"],
  ["James Johnson", "0710111213", "Software Engineer", "28/10/2023"],
  ["Sophia Davis", "0723242526", "Customer Support Specialist", "17/02/2016"],
  ["Noah Martinez", "0756575859", "Product Manager", "22/04/2018"],
  ["Charlotte Brown", "0781828384", "Marketing Specialist", "10/06/2022"],
  ["Henry Rodriguez", "0734353637", "Sales Representative", "04/08/2015"],
  ["Olivia Miller", "0769676564", "Software Engineer", "12/03/2020"],
  ["Lucas Wilson", "0790919293", "Data Analyst", "24/05/2021"],
  ["Evelyn Smith", "0743454647", "UX Designer", "06/11/2019"],
  [
    "William Anderson",
    "0776777879",
    "Human Resources Generalist",
    "01/09/2017",
  ],
  ["Mia Thomas", "0789909192", "Financial Analyst", "26/12/2022"],
  ["Benjamin Hernandez", "0713141516", "Operations Manager", "11/07/2016"],
  ["Liam Davis", "0758596061", "Software Engineer", "14/03/2024"],
  [
    "Isabella Taylor",
    "0793949596",
    "Customer Support Specialist",
    "07/05/2019",
  ],
  ["Elijah Lopez", "0745464748", "Product Manager", "20/09/2021"],
  ["Amelia Williams", "0788998899", "Marketing Specialist", "02/02/2016"],
  ["James Smith", "0720212223", "Sales Representative", "27/11/2020"],
  ["Sophia Gonzalez", "0753545556", "Data Analyst", "18/08/2017"],
  ["Noah Johnson", "0766655544", "UX Designer", "10/10/2022"],
  [
    "Charlotte Martinez",
    "0799887766",
    "Human Resources Generalist",
    "03/04/2018",
  ],
  ["Henry Davis", "0712345678", "Financial Analyst", "24/01/2023"],
  ["Olivia Hernandez", "0787654321", "Operations Manager", "16/09/2015"],
  ["Lucas Thomas", "0755443322", "Software Engineer", "28/11/2022"],
  ["Evelyn Miller", "0711223344", "Customer Support Specialist", "09/06/2018"],
  ["William Garcia", "0733445566", "Product Manager", "21/01/2021"],
  ["Mia Wilson", "0766778899", "Marketing Specialist", "13/04/2017"],
  ["Benjamin Brown", "0799001122", "Data Analyst", "05/10/2023"],
  ["Liam Anderson", "0745678910", "UX Designer", "17/12/2015"],
  ["Isabella Lopez", "0710203040", "Human Resources Generalist", "30/03/2022"],
  ["Elijah Davis", "0750607080", "Financial Analyst", "23/07/2019"],
  ["Amelia Taylor", "0780901020", "Operations Manager", "08/02/2017"],
  ["James Rodriguez", "0720304050", "Software Engineer", "19/05/2024"],
  ["Sophia Johnson", "0760708090", "Customer Support Specialist", "12/09/2020"],
];

export const exampleCertificates = [
  ["CCNA", "22/4/2022", "22/4/2024", "Network", "45"],
  [
    "AWS Certified Solutions Architect",
    "15/10/2023",
    "15/10/2026",
    "Cloud",
    "60",
  ],
  ["PMP", "1/1/2024", "1/1/2027", "Project Management", "55"],
  ["Certified ScrumMaster", "5/3/2023", "5/3/2025", "Agile", "40"],
  ["CISSP", "10/7/2023", "10/7/2026", "Cybersecurity", "70"],
  ["Google Associate Cloud Engineer", "20/9/2022", "20/9/2024", "Cloud", "50"],
  ["CompTIA Security+", "12/2/2023", "12/2/2026", "Cybersecurity", "45"],
  [
    "Microsoft Certified: Azure Administrator Associate",
    "8/5/2023",
    "8/5/2025",
    "Cloud",
    "55",
  ],
  ["ITIL Foundation", "3/6/2022", "3/6/2025", "IT Service Management", "35"],
  [
    "Oracle Certified Professional, Java SE 11 Developer",
    "18/11/2023",
    "18/11/2026",
    "Software Development",
    "60",
  ],
  ["RHCSA", "25/1/2024", "25/1/2027", "System Administration", "50"],
  [
    "Certified Kubernetes Administrator",
    "14/8/2023",
    "14/8/2026",
    "DevOps",
    "65",
  ],
  ["CEH", "2/4/2023", "2/4/2026", "Cybersecurity", "50"],
  [
    "VMware Certified Professional",
    "7/12/2022",
    "7/12/2025",
    "Virtualization",
    "55",
  ],
  [
    "Cisco Certified CyberOps Associate",
    "11/3/2024",
    "11/3/2027",
    "Cybersecurity",
    "40",
  ],
  ["LPI Linux Essentials", "28/6/2022", "28/6/2025", "Linux", "30"],
  ["Salesforce Certified Administrator", "19/9/2023", "19/9/2026", "CRM", "45"],
  ["CCNP Enterprise", "2/10/2024", "2/10/2027", "Network", "65"],
  [
    "AWS Certified Developer – Associate",
    "16/5/2023",
    "16/5/2026",
    "Cloud",
    "55",
  ],
  ["PRINCE2 Foundation", "22/7/2022", "22/7/2025", "Project Management", "40"],
  [
    "Certified Ethical Hacker (CEH) v11",
    "3/1/2023",
    "3/1/2026",
    "Cybersecurity",
    "60",
  ],
  [
    "Tableau Desktop Certified Associate",
    "8/8/2023",
    "8/8/2026",
    "Data Analytics",
    "50",
  ],
  ["JNCIA-Junos", "14/11/2022", "14/11/2025", "Network", "45"],
  [
    "Microsoft Certified: Power Platform Developer Associate",
    "20/2/2024",
    "20/2/2027",
    "Business Apps",
    "50",
  ],
  [
    "Six Sigma Green Belt",
    "25/5/2023",
    "25/5/2026",
    "Process Improvement",
    "45",
  ],
  [
    "Oracle Cloud Infrastructure Foundations Associate",
    "1/4/2022",
    "1/4/2025",
    "Cloud",
    "35",
  ],
  ["CompTIA A+", "10/1/2023", "10/1/2026", "IT Support", "40"],
  [
    "AWS Certified SysOps Administrator - Associate",
    "15/6/2023",
    "15/6/2026",
    "Cloud",
    "55",
  ],
  [
    "Microsoft Certified: Azure Solutions Architect Expert",
    "20/9/2023",
    "20/9/2026",
    "Cloud",
    "70",
  ],
  ["CCDE", "5/12/2023", "5/12/2026", "Network", "80"],
  ["SAFe 5 Agilist", "1/3/2024", "1/3/2027", "Agile", "50"],
  ["CompTIA Network+", "18/8/2022", "18/8/2025", "Network", "40"],
  [
    "Certified Kubernetes Application Developer",
    "22/10/2023",
    "22/10/2026",
    "DevOps",
    "60",
  ],
  ["CISSP-ISSAP", "7/1/2024", "7/1/2027", "Cybersecurity", "75"],
  [
    "Google Professional Cloud Architect",
    "12/5/2023",
    "12/5/2026",
    "Cloud",
    "70",
  ],
  [
    "Microsoft Certified: Azure Developer Associate",
    "14/9/2022",
    "14/9/2025",
    "Cloud",
    "50",
  ],
  ["CISA", "2/11/2023", "2/11/2026", "Auditing", "60"],
  ["OCP MySQL 5.7 Developer", "20/1/2023", "20/1/2026", "Database", "55"],
  ["Cisco DevNet Associate", "16/4/2024", "16/4/2027", "Automation", "45"],
  [
    "VMware Certified Advanced Professional",
    "8/7/2023",
    "8/7/2026",
    "Virtualization",
    "65",
  ],
  [
    "AWS Certified Machine Learning - Specialty",
    "25/11/2023",
    "25/11/2026",
    "AI/ML",
    "75",
  ],
  ["LPIC-1", "1/2/2023", "1/2/2026", "Linux", "40"],
  [
    "Salesforce Certified Platform Developer I",
    "10/3/2024",
    "10/3/2027",
    "Software Development",
    "55",
  ],
  ["PMP Agile Certified Practitioner", "18/6/2023", "18/6/2026", "Agile", "50"],
  [
    "Microsoft Certified: Power BI Data Analyst Associate",
    "22/8/2023",
    "22/8/2026",
    "Data Analytics",
    "45",
  ],
  ["CompTIA PenTest+", "28/12/2023", "28/12/2026", "Cybersecurity", "55"],
  [
    "Cisco CCIE Enterprise Infrastructure",
    "5/5/2024",
    "5/5/2027",
    "Network",
    "85",
  ],
  ["Certified Scrum Product Owner", "15/1/2023", "15/1/2025", "Agile", "45"],
  [
    "Google Professional Data Engineer",
    "10/10/2023",
    "10/10/2026",
    "Data Engineering",
    "65",
  ],
  [
    "AWS Certified Data Analytics - Specialty",
    "20/4/2024",
    "20/4/2027",
    "Data Analytics",
    "60",
  ],
  ["(ISC)2 CCSP", "2/6/2023", "2/6/2026", "Cloud Security", "60"],
];

export const exampleRequests = [
  [
    "Senior Front-End Developer Request",
    "I would like to etc etc",
    "Jason Mamomoa",
    "Roadmap Request",
    "Finished ✅",
  ],
  [
    "New Feature Request: Dark Mode",
    "Add a dark mode theme for the user interface.",
    "Sarah Connor",
    "Feature Request",
    "In Progress ⚙️",
  ],
  [
    "Database Performance Issue",
    "Investigate and resolve slow query times on the main database.",
    "John Doe",
    "Bug Report",
    "Pending ⏳",
  ],
  [
    "UI/UX Redesign for Checkout",
    "Redesign the checkout flow to improve conversion rates.",
    "Jane Smith",
    "Design Request",
    "Finished ✅",
  ],
  [
    "Security Audit for User Authentication",
    "Perform a comprehensive security audit on the login system.",
    "Alex Chen",
    "Security Request",
    "In Progress ⚙️",
  ],
  [
    "Update API Documentation",
    "Revise and update the API documentation to reflect recent changes.",
    "Mike Johnson",
    "Documentation",
    "Pending ⏳",
  ],
  [
    "Mobile App Bug Fix: Crashes on iOS",
    "The mobile app is crashing on iOS 17 devices.",
    "Lisa Ray",
    "Bug Report",
    "In Progress ⚙️",
  ],
  [
    "Marketing Campaign Integration",
    "Integrate new tracking scripts for the upcoming marketing campaign.",
    "David Lee",
    "Integration Request",
    "Finished ✅",
  ],
  [
    "Server Migration to AWS",
    "Migrate all production servers from on-premise to AWS cloud.",
    "Chris Evans",
    "Infrastructure",
    "Pending ⏳",
  ],
  [
    "New Dashboard for Analytics",
    "Create a new analytics dashboard for the marketing team.",
    "Emma Watson",
    "Reporting Request",
    "Finished ✅",
  ],
  [
    "Refactor Legacy Code in Payment Module",
    "Rewrite the old payment processing code to a modern framework.",
    "Paul Rudd",
    "Refactoring",
    "In Progress ⚙️",
  ],
  [
    "Add Support for Multiple Languages",
    "Implement internationalization (i18n) for the application.",
    "Rachel Green",
    "Feature Request",
    "Pending ⏳",
  ],
  [
    "Training Request: Python for Data Science",
    "I would like to request training sessions on Python for data analysis.",
    "Ben Affleck",
    "Training Request",
    "Finished ✅",
  ],
  [
    "Issue with User Profile Editing",
    "Users are unable to save changes to their profile information.",
    "Mia Khalifa",
    "Bug Report",
    "In Progress ⚙️",
  ],
  [
    "Third-Party Library Update",
    "Update all third-party libraries to their latest versions.",
    "Tom Hanks",
    "Maintenance",
    "Pending ⏳",
  ],
  [
    "Content Management System Integration",
    "Integrate a new CMS to manage website content more efficiently.",
    "Jennifer Aniston",
    "Integration Request",
    "Finished ✅",
  ],
  [
    "Accessibility Audit (WCAG Compliance)",
    "Perform an audit to ensure the website is WCAG 2.1 compliant.",
    "Will Smith",
    "Compliance Request",
    "In Progress ⚙️",
  ],
  [
    "Feature Toggle for A/B Testing",
    "Implement a feature toggle system for A/B testing new designs.",
    "Angelina Jolie",
    "Feature Request",
    "Pending ⏳",
  ],
  [
    "Create New Microservice for Notifications",
    "Develop a new microservice to handle all user notifications.",
    "Brad Pitt",
    "Architecture Request",
    "Finished ✅",
  ],
  [
    "Fix Broken Links on Homepage",
    "Multiple links on the homepage are leading to 404 pages.",
    "Sandra Bullock",
    "Bug Report",
    "In Progress ⚙️",
  ],
  [
    "Upgrade Database to PostgreSQL 15",
    "Upgrade the current database from PostgreSQL 13 to 15.",
    "Keanu Reeves",
    "Infrastructure",
    "Finished ✅",
  ],
  [
    "Bug Report: Incorrect Reporting Data",
    "The monthly sales reports are showing incorrect figures.",
    "Morgan Freeman",
    "Bug Report",
    "Pending ⏳",
  ],
  [
    "Mobile App: Add Push Notifications",
    "Integrate push notifications for new messages and updates.",
    "Robert Downey Jr.",
    "Feature Request",
    "In Progress ⚙️",
  ],
  [
    "Redesign of Internal Wiki",
    "Update the design and structure of the company's internal wiki.",
    "Scarlett Johansson",
    "Design Request",
    "Finished ✅",
  ],
  [
    "Implement SSO with Okta",
    "Set up Single Sign-On (SSO) using Okta for employee access.",
    "Chris Pratt",
    "Security Request",
    "Pending ⏳",
  ],
  [
    "Feature Request: User Role Permissions",
    "Add more granular user role permissions for administrators.",
    "Vin Diesel",
    "Feature Request",
    "In Progress ⚙️",
  ],
  [
    "Bug Report: Login Timeout Issues",
    "Users are being logged out unexpectedly after short periods.",
    "Dwayne Johnson",
    "Bug Report",
    "Finished ✅",
  ],
  [
    "SEO Optimization for Blog Posts",
    "Perform SEO optimization on all recent blog posts.",
    "Leonardo DiCaprio",
    "Marketing Request",
    "In Progress ⚙️",
  ],
  [
    "Create a New Landing Page",
    "Design and develop a new landing page for the upcoming product launch.",
    "Tom Holland",
    "Design Request",
    "Pending ⏳",
  ],
  [
    "Feature Request: In-App Chat Support",
    "Add a live chat support feature directly within the application.",
    "Zendaya Coleman",
    "Feature Request",
    "Finished ✅",
  ],
  [
    "Bug Report: Incorrect Billing for Subscriptions",
    "Customers are being billed the wrong amount for their subscriptions.",
    "Ryan Reynolds",
    "Bug Report",
    "In Progress ⚙️",
  ],
  [
    "Upgrade to React 18",
    "Upgrade the front-end codebase from React 17 to React 18.",
    "Blake Lively",
    "Maintenance",
    "Pending ⏳",
  ],
  [
    "Integrate with Stripe for Payments",
    "Integrate Stripe as a new payment gateway option.",
    "Harrison Ford",
    "Integration Request",
    "Finished ✅",
  ],
  [
    "Data Migration from Old System",
    "Migrate all historical customer data from the legacy system.",
    "Daisy Ridley",
    "Data Request",
    "In Progress ⚙️",
  ],
  [
    "Request for New Development Environment",
    "Set up a new, standardized development environment for the team.",
    "John Boyega",
    "Infrastructure",
    "Pending ⏳",
  ],
  [
    "Bug Report: Email Notifications Not Sending",
    "Automated email notifications are failing to send to users.",
    "Adam Driver",
    "Bug Report",
    "Finished ✅",
  ],
  [
    "Add 2FA to User Accounts",
    "Implement two-factor authentication (2FA) for all user accounts.",
    "Natalie Portman",
    "Security Request",
    "In Progress ⚙️",
  ],
  [
    "Design New Email Templates",
    "Create new, modern email templates for marketing and transactional emails.",
    "Chris Hemsworth",
    "Design Request",
    "Pending ⏳",
  ],
  [
    "Request for Performance Testing",
    "Perform load and stress testing on the application before launch.",
    "Tessa Thompson",
    "Testing Request",
    "Finished ✅",
  ],
  [
    "Fix Styling Issues on Safari",
    "Correct various styling and layout issues that appear only on Safari.",
    "Mark Ruffalo",
    "Bug Report",
    "In Progress ⚙️",
  ],
  [
    "Upgrade to Node.js 18",
    "Upgrade the back-end from Node.js 16 to Node.js 18.",
    "Lupita Nyong'o",
    "Maintenance",
    "Pending ⏳",
  ],
  [
    "Feature Request: User Feedback Portal",
    "Build a new portal where users can submit and vote on feature ideas.",
    "Chadwick Boseman",
    "Feature Request",
    "Finished ✅",
  ],
  [
    "Bug Report: Search Functionality is Broken",
    "The search bar on the website is not returning any results.",
    "Michael B. Jordan",
    "Bug Report",
    "In Progress ⚙️",
  ],
  [
    "Create a New API Endpoint",
    "Develop a new API endpoint to retrieve all user data for reporting.",
    "Letitia Wright",
    "API Request",
    "Pending ⏳",
  ],
  [
    "Request for a CDN",
    "Implement a Content Delivery Network (CDN) to speed up asset loading.",
    "Danai Gurira",
    "Infrastructure",
    "Finished ✅",
  ],
  [
    "Bug Report: Infinite Loading on User Feed",
    "The user feed on the mobile app gets stuck in an infinite loading state.",
    "Winston Duke",
    "Bug Report",
    "In Progress ⚙️",
  ],
  [
    "Feature Request: Payment History",
    "Add a page where users can view and download their payment history.",
    "Brie Larson",
    "Feature Request",
    "Pending ⏳",
  ],
  [
    "Refactor Microservice Communications",
    "Refactor the communication between microservices to use a message queue.",
    "Samuel L. Jackson",
    "Refactoring",
    "Finished ✅",
  ],
  [
    "Request for new internal tools",
    "I would like a new tool to handle some of my processes.",
    "Ryan Gosling",
    "Roadmap Request",
    "In Progress ⚙️",
  ],
  [
    "Bug Report: Broken Sign Up Page",
    "Users cannot successfully sign up for a new account.",
    "Chris Pine",
    "Bug Report",
    "Pending ⏳",
  ],
];

export const exampleRoadmaps = [
  ["Junior Front-End", "8", "3 weeks", "█████░░░░░ 5/10 "],
  ["React Fundamentals", "6", "1 month", "█████░░░░░ 5/10 "],
  ["Node.js Backend", "10", "2 months", "███████░░░ 7/10 "],
  ["Full-Stack JavaScript", "15", "4 months", "█████████░ 9/10 "],
  ["Data Structures & Algorithms", "12", "3 months", "████████░░ 8/10 "],
  ["Cloud Practitioner (AWS)", "7", "6 weeks", "██████░░░░ 6/10 "],
  ["Machine Learning Basics", "9", "2.5 months", "████████░░ 8/10 "],
  ["Mobile Development (React Native)", "11", "3 months", "████████░░ 8/10 "],
  ["DevOps Engineer", "14", "5 months", "█████████░ 9/10 "],
  ["UI/UX Designer", "5", "1 month", "████░░░░░░ 4/10 "],
  ["Cybersecurity Analyst", "10", "4 months", "███████░░░ 7/10 "],
  ["Database Administrator", "7", "2 months", "█████░░░░░ 5/10 "],
  ["Python for Data Science", "8", "2 months", "██████░░░░ 6/10 "],
  ["Game Development (Unity)", "13", "4.5 months", "████████░░ 8/10 "],
  ["API Design", "6", "1.5 months", "█████░░░░░ 5/10 "],
  ["Web Accessibility", "4", "3 weeks", "████░░░░░░ 4/10 "],
  ["TypeScript Deep Dive", "5", "1 month", "██████░░░░ 6/10 "],
  ["Containerization (Docker)", "7", "2 months", "██████░░░░ 6/10 "],
  ["Kubernetes", "10", "3 months", "████████░░ 8/10 "],
  ["Blockchain Fundamentals", "8", "3 months", "████████░░ 8/10 "],
  ["GraphQL API", "5", "1 month", "██████░░░░ 6/10 "],
  ["Vue.js Framework", "6", "1.5 months", "█████░░░░░ 5/10 "],
  ["Angular Framework", "7", "2 months", "██████░░░░ 6/10 "],
  ["Serverless Architecture", "9", "2.5 months", "███████░░░ 7/10 "],
  ["GCP Cloud Engineer", "8", "3 months", "███████░░░ 7/10 "],
  ["Azure Cloud Engineer", "8", "3 months", "███████░░░ 7/10 "],
  ["Mobile UI/UX", "6", "1 month", "█████░░░░░ 5/10 "],
  ["Data Visualization (D3.js)", "9", "2 months", "████████░░ 8/10 "],
  ["WebRTC", "7", "2 months", "████████░░ 8/10 "],
  ["WebSockets", "4", "3 weeks", "████░░░░░░ 4/10 "],
  ["CI/CD Pipelines", "6", "2 months", "██████░░░░ 6/10 "],
  ["Go Programming", "10", "3 months", "███████░░░ 7/10 "],
  ["Rust Programming", "12", "4 months", "████████░░ 8/10 "],
  ["Advanced CSS", "5", "1 month", "████░░░░░░ 4/10 "],
  ["Web Security", "8", "2.5 months", "███████░░░ 7/10 "],
  ["Automated Testing", "6", "2 months", "██████░░░░ 6/10 "],
  ["Backend for Front-End (BFF)", "7", "2 months", "███████░░░ 7/10 "],
  ["Monorepo Architecture", "5", "1 month", "██████░░░░ 6/10 "],
  ["Design Systems", "9", "3 months", "███████░░░ 7/10 "],
  ["Svelte Framework", "4", "3 weeks", "████░░░░░░ 4/10 "],
  ["E-commerce Solutions", "11", "3.5 months", "████████░░ 8/10 "],
  ["Payment Gateway Integration", "6", "1.5 months", "███████░░░ 7/10 "],
  ["SEO Optimization", "5", "1 month", "████░░░░░░ 4/10 "],
  ["Performance Tuning", "8", "2 months", "███████░░░ 7/10 "],
  ["JAMstack", "6", "2 months", "█████░░░░░ 5/10 "],
  ["Web Components", "5", "1 month", "█████░░░░░ 5/10 "],
  ["WebAssembly", "9", "3 months", "█████████░ 9/10 "],
  ["Server-Side Rendering (Next.js)", "7", "2 months", "██████░░░░ 6/10 "],
  ["Static Site Generation (Gatsby)", "5", "1.5 months", "█████░░░░░ 5/10 "],
  ["Progressive Web Apps (PWA)", "6", "2 months", "██████░░░░ 6/10 "],
  ["IoT Development", "10", "4 months", "████████░░ 8/10 "],
  ["Computer Vision", "11", "5 months", "█████████░ 9/10 "],
  ["NLP", "12", "5 months", "█████████░ 9/10 "],
  ["Robotics", "15", "6 months", "██████████ 10/10 "],
  ["Ethical Hacking", "13", "5 months", "█████████░ 9/10 "],
  ["Forensic Analysis", "9", "3 months", "███████░░░ 7/10 "],
  ["Network Engineering", "8", "3 months", "███████░░░ 7/10 "],
  ["System Administrator", "7", "2 months", "██████░░░░ 6/10 "],
  ["Cloud Security", "10", "4 months", "████████░░ 8/10 "],
  ["Digital Marketing", "6", "2 months", "████░░░░░░ 4/10 "],
  ["Content Management Systems (CMS)", "5", "1.5 months", "████░░░░░░ 4/10 "],
  ["Agile Methodology", "4", "3 weeks", "████░░░░░░ 4/10 "],
  ["Scrum Master", "5", "1 month", "█████░░░░░ 5/10 "],
  ["Product Management", "8", "2.5 months", "██████░░░░ 6/10 "],
  ["Technical Writing", "6", "2 months", "████░░░░░░ 4/10 "],
  ["UI Animation", "7", "2 months", "█████░░░░░ 5/10 "],
  ["3D Modeling", "9", "3 months", "███████░░░ 7/10 "],
  ["Audio Engineering", "10", "4 months", "████████░░ 8/10 "],
  ["Video Production", "8", "3 months", "██████░░░░ 6/10 "],
  ["UX Research", "6", "2 months", "█████░░░░░ 5/10 "],
  ["Accessibility Auditing", "5", "1 month", "█████░░░░░ 5/10 "],
  ["Web Performance Auditing", "4", "3 weeks", "████░░░░░░ 4/10 "],
  ["Functional Programming", "8", "3 months", "███████░░░ 7/10 "],
  ["OOP Principles", "6", "2 months", "██████░░░░ 6/10 "],
  ["Test-Driven Development (TDD)", "7", "2.5 months", "███████░░░ 7/10 "],
  ["Behavior-Driven Development (BDD)", "6", "2 months", "██████░░░░ 6/10 "],
  ["Data Engineering", "11", "4 months", "█████████░ 9/10 "],
  ["Big Data Processing (Spark)", "12", "5 months", "█████████░ 9/10 "],
  ["Quantum Computing", "15", "6 months", "██████████ 10/10 "],
  ["Cryptography", "10", "4 months", "████████░░ 8/10 "],
  ["Information Theory", "9", "3 months", "████████░░ 8/10 "],
  ["Compiler Design", "13", "5 months", "█████████░ 9/10 "],
  ["Operating Systems", "11", "4 months", "█████████░ 9/10 "],
  ["Distributed Systems", "12", "5 months", "█████████░ 9/10 "],
  ["Embedded Systems", "10", "4 months", "████████░░ 8/10 "],
  ["System on a Chip (SoC)", "14", "6 months", "██████████ 10/10 "],
  ["FPGA Development", "13", "5.5 months", "█████████░ 9/10 "],
  ["Network Security", "10", "4 months", "████████░░ 8/10 "],
  ["Red Team Operations", "12", "5 months", "█████████░ 9/10 "],
  ["Blue Team Operations", "11", "4 months", "████████░░ 8/10 "],
  ["Incident Response", "8", "3 months", "███████░░░ 7/10 "],
  ["Penetration Testing", "9", "3 months", "████████░░ 8/10 "],
  ["Social Engineering", "7", "2 months", "█████░░░░░ 5/10 "],
  ["Physical Security", "6", "1.5 months", "████░░░░░░ 4/10 "],
  ["Data Governance", "8", "2 months", "██████░░░░ 6/10 "],
  ["Compliance and Auditing", "7", "2.5 months", "██████░░░░ 6/10 "],
  ["Risk Management", "9", "3 months", "███████░░░ 7/10 "],
  ["Business Continuity Planning", "8", "2 months", "██████░░░░ 6/10 "],
  ["Disaster Recovery", "7", "2 months", "██████░░░░ 6/10 "],
  ["Financial Technology (FinTech)", "10", "4 months", "████████░░ 8/10 "],
  ["Healthcare Technology (HealthTech)", "9", "3 months", "███████░░░ 7/10 "],
  ["Educational Technology (EdTech)", "8", "2 months", "██████░░░░ 6/10 "],
  ["Augmented Reality (AR)", "11", "4 months", "█████████░ 9/10 "],
  ["Virtual Reality (VR)", "12", "5 months", "█████████░ 9/10 "],
  ["Internet of Things (IoT)", "10", "4 months", "████████░░ 8/10 "],
  ["Digital Twin", "11", "4.5 months", "█████████░ 9/10 "],
  ["Edge Computing", "9", "3 months", "███████░░░ 7/10 "],
  ["Fog Computing", "8", "2.5 months", "██████░░░░ 6/10 "],
];

// Name, Progress
// Name, Progress
export const exampleActiveEmployees = [
  ["Alex Johnson", "█████░ 5/6 "],
  ["Maria Rodriguez", "███░░░ 3/5 "],
  ["Chris Lee", "█████░ 5/6 "],
  ["Sarah Chen", "██████ 6/6 "],
  ["David Miller", "██░░░░ 2/6 "],
  ["Jessica White", "████░░ 4/6 "],
  ["Daniel Kim", "█████░ 5/6 "],
  ["Emily Davis", "████░░ 4/6 "],
  ["James Wilson", "██████ 6/6 "],
  ["Olivia Brown", "█░░░░░ 1/6 "],
  ["Ethan Taylor", "████░░ 4/6 "],
  ["Sophia Martinez", "█████░ 5/6 "],
  ["Liam Moore", "████░░ 4/6 "],
  ["Ava Garcia", "██████ 6/6 "],
  ["Noah Clark", "███░░░ 3/6 "],
  ["Isabella Lopez", "█████░ 5/6 "],
  ["Mason Hall", "████░░ 4/6 "],
  ["Chloe Adams", "██████ 6/6 "],
  ["Jacob Baker", "██░░░░ 2/6 "],
  ["Mia Green", "█████░ 5/6 "],
  ["William Evans", "████░░ 4/6 "],
  ["Harper King", "█████░ 5/6 "],
  ["Logan Hill", "██████ 6/6 "],
  ["Charlotte Scott", "██░░░░ 2/6 "],
  ["Benjamin Carter", "████░░ 4/6 "],
  ["Amelia Perez", "█████░ 5/6 "],
  ["Elijah Roberts", "████░░ 4/6 "],
  ["Abigail Turner", "██████ 6/6 "],
  ["Lucas Mitchell", "███░░░ 3/6 "],
  ["Emma Phillips", "█████░ 5/6 "],
  ["Michael Campbell", "████░░ 4/6 "],
  ["Avery Parker", "█████░ 5/6 "],
  ["Sebastian Evans", "██████ 6/6 "],
  ["Aria Collins", "██░░░░ 2/6 "],
  ["Grace Stewart", "████░░ 4/6 "],
  ["Jack Morris", "█████░ 5/6 "],
  ["Ella Cook", "████░░ 4/6 "],
  ["Leo Rogers", "██████ 6/6 "],
  ["Lily Bell", "█░░░░░ 1/6 "],
  ["Ryan Murphy", "████░░ 4/6 "],
  ["Zoe Rivera", "█████░ 5/6 "],
  ["Jackson Cooper", "████░░ 4/6 "],
  ["Penelope Bailey", "██████ 6/6 "],
  ["Gabriel Howard", "███░░░ 3/6 "],
  ["Layla Brooks", "█████░ 5/6 "],
  ["Wyatt Kelly", "████░░ 4/6 "],
  ["Stella Hughes", "█████░ 5/6 "],
  ["Caleb Edwards", "██████ 6/6 "],
  ["Hannah Gray", "██░░░░ 2/6 "],
  ["Carter James", "████░░ 4/6 "],
  ["Lillian Peterson", "█████░ 5/6 "],
  ["Jayden Foster", "████░░ 4/6 "],
  ["Scarlett Simmons", "██████ 6/6 "],
  ["Owen Ross", "███░░░ 3/6 "],
  ["Aubrey Reed", "█████░ 5/6 "],
  ["Julian Morgan", "████░░ 4/6 "],
  ["Elizabeth Long", "█████░ 5/6 "],
  ["Lincoln Cooper", "██████ 6/6 "],
  ["Aaliyah Butler", "██░░░░ 2/6 "],
  ["Josiah Perry", "████░░ 4/6 "],
  ["Victoria Price", "█████░ 5/6 "],
  ["Isaiah Coleman", "████░░ 4/6 "],
  ["Madison Rogers", "██████ 6/6 "],
  ["Cora Ward", "█░░░░░ 1/6 "],
  ["Nathan Fisher", "████░░ 4/6 "],
  ["Paisley Watson", "█████░ 5/6 "],
  ["Nolan Russell", "████░░ 4/6 "],
  ["Elena Griffin", "██████ 6/6 "],
  ["Connor Powell", "███░░░ 3/6 "],
  ["Chloe Hayes", "█████░ 5/6 "],
  ["Hunter Jenkins", "████░░ 4/6 "],
  ["Addison Wood", "█████░ 5/6 "],
  ["Dominic Barnes", "██████ 6/6 "],
  ["Skylar Henderson", "██░░░░ 2/6 "],
  ["Lucy Ramirez", "████░░ 4/6 "],
  ["Andrew Bryant", "█████░ 5/6 "],
  ["Violet King", "████░░ 4/6 "],
  ["Brandon Rivera", "██████ 6/6 "],
  ["Savannah Hughes", "███░░░ 3/6 "],
  ["Adrian Peterson", "█████░ 5/6 "],
  ["Brooklyn Gray", "████░░ 4/6 "],
  ["Jordan Baker", "█████░ 5/6 "],
  ["Kennedy Collins", "██████ 6/6 "],
  ["Cole Stewart", "██░░░░ 2/6 "],
  ["Gabriella Foster", "████░░ 4/6 "],
  ["Alexandro Simmons", "█████░ 5/6 "],
  ["Riley Long", "████░░ 4/6 "],
  ["Audrey Watson", "██████ 6/6 "],
  ["Ian Ross", "█░░░░░ 1/6 "],
  ["Taylor Reed", "████░░ 4/6 "],
  ["Sarah Morgan", "█████░ 5/6 "],
  ["Blake Anderson", "████░░ 4/6 "],
  ["Jasmine Evans", "██████ 6/6 "],
  ["Kayden Bell", "███░░░ 3/6 "],
  ["Madeline Perry", "█████░ 5/6 "],
  ["Asher Coleman", "████░░ 4/6 "],
  ["Serenity Powell", "█████░ 5/6 "],
  ["Gavin Hayes", "██████ 6/6 "],
];

export const exampleCertifications = [
  { title: "Project Management Professional (PMP)" },
  { title: "Certified Information Systems Security Professional (CISSP)" },
  { title: "AWS Certified Solutions Architect" },
  { title: "Google Professional Data Engineer" },
  { title: "Certified ScrumMaster (CSM)" },
  { title: "Cisco Certified Network Associate (CCNA)" },
  { title: "Certified Ethical Hacker (CEH)" },
  { title: "CompTIA A+" },
  { title: "Microsoft Certified: Azure Administrator Associate" },
  { title: "Certified Public Accountant (CPA)" },
  { title: "Certified Financial Analyst (CFA)" },
  { title: "Professional Engineer (PE)" },
  { title: "SHRM-CP" },
  { title: "ISTQB Certified Tester" },
  { title: "Certified Kubernetes Administrator (CKA)" },
  { title: "ITIL 4 Foundation" },
  { title: "Six Sigma Black Belt" },
  { title: "Oracle Certified Professional (OCP)" },
  { title: "Red Hat Certified System Administrator (RHCSA)" },
];
